# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pies2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pies2
  pod 'FacebookCore’
  pod 'FacebookLogin'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'RealmSwift'
  


end
